import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';
import { UUID } from '../../shared/types/uuid.type';

/**
 * Customer entity representing a Customer table in the database.
 * ID is autogenerated and of type UUID.
 */
@Entity()
export class Customer {
  @PrimaryGeneratedColumn('uuid')
  id: UUID;

  @Column()
  firstName: string;

  @Column()
  lastName: string;

  @Column()
  email: string;

  @Column()
  phone: string;
}
